# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "akhachatS" do |server|
    server.vm.box = "generic/ubuntu2004" # might be changed
    server.vm.hostname = "akhachatS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 512 
      vb.cpus = 1 
    end

    server.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" sh -
      sudo systemctl enable k3s
      sudo systemctl start k3s

      sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/token
    SHELL
  end
  config.vm.define "akhachatSW" do |server_worker|
    server_worker.vm.box = "generic/ubuntu2004"
    server_worker.vm.hostname = "akhachatSW"
    server_worker.vm.network "private_network", ip: "192.168.56.111"
    server_worker.vm.provider "virtualbox" do |vb|
      vb.memory = 512 
      vb.cpus = 1 
    end

    
    server_worker.vm.provision "shell", inline: <<-SHELL
      cp /vagrant/token /tmp/token

      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(cat /tmp/token) sh -
      sudo systemctl enable k3s
      sudo systemctl start k3s

      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x kubectl
      sudo mv kubectl /usr/local/bin/
    SHELL
  end
  
  config.ssh.insert_key = false
  config.ssh.private_key_path = "~/.ssh/id_rsa" # need to be refactored
end

